# Generated by Django 5.2.3 on 2025-07-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='email',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='phone_number',
        ),
    ]
