# Generated by Django 5.2.3 on 2025-07-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0002_remove_confession_deadline_remove_confession_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='confession_image',
        ),
    ]
