# Generated by Django 5.2.3 on 2025-07-23 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0003_remove_confession_confession_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='name',
        ),
        migrations.AddField(
            model_name='confession',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
