# Generated by Django 5.2.3 on 2025-07-25 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0004_remove_confession_name_confession_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='hearts',
            field=models.ManyToManyField(blank=True, related_name='liked_confessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
