# Generated by Django 5.2.3 on 2025-07-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/9308/9308904.png', max_length=200),
        ),
    ]
