# Generated by Django 5.2.3 on 2025-07-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('confession_image', models.ImageField(blank=True, null=True, upload_to='confession_images/')),
                ('confession', models.TextField()),
            ],
        ),
    ]
