# Generated by Django 5.2.3 on 2025-07-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confessions',
        ),
    ]
